<!DOCTYPE html>
<html>
<body>

<h2>JavaScript try catch</h2>

<p>Please input a number between 5 and 10:</p>

<input id="demo" type="text">
<button type="button" onclick="myFunction()">Test Input</button>

<p id="p01"></p>

<script>
function myFunction() {
  const message = document.getElementById("p01");
  message.innerHTML = "";
  let x = document.getElementById("demo").value;
  try {
    if(x == "")  throw "is empty";
    if(isNaN(x)) throw "is not a number";
    x = Number(x);
    if(x > 10)   throw "is too high";
    if(x < 5)  throw "is too low";
  }
  catch(err) {
    message.innerHTML = "Input " + err;
  }
  finally {
    document.getElementById("demo").value = "";
  }
}
</script>

</body>
</html>











<!-- -->
<!-- -->
<!--

JavaScript Errors - Throw and Try to Catch


-->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!--

The finally Statement


The finally statement lets you execute code, after try and catch, regardless of the result:


Syntax:


try {
  Block of code to try
}
catch(err) {
  Block of code to handle errors
}
finally {
  Block of code to be executed regardless of the try / catch result
}


-->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!--

Error Object Properties


Property                Description

name                    Sets or returns an error name
message                 Sets or returns an error message (a string)


-->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!--


Error Name Values

Six different values can be returned by the error name property:



Error Name                  Description

EvalError                   An error has occurred in the eval() function
RangeError                  A number "out of range" has occurred
ReferenceError              An illegal reference has occurred
SyntaxError                 A syntax error has occurred
TypeError                   A type error has occurred
URIError                    An error in encodeURI() has occurred



-->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
<!-- -->
